name: Deployment
on:
  push:
    branches:
      - production
      
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: docker compose down
      - run: docker compose up -d
      - run: docker compose exec kelolafoto_app php artisan migrate
