name: Deployment
on:
  push:
    branches:
      - production
      
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: docker compose -f docker-compose.prod.yml down
      - run: docker compose -f docker-compose.prod.yml build --no-cache
      - run: docker compose -f docker-compose.prod.yml up -d
      - run: docker compose -f docker-compose.prod.yml exec kelolafoto_app php artisan migrate
